Repository Rubensrvsc/atividade-1-cesar, pull requests merged in 2022-11, with the labels that each got.

#1 feat-options-products
  marktplace.rb
Labels: bug

#2 Add to do list and menu to products
  marktplace.rb
Labels: documentation

#3 Add menu callback and count
  marktplace.rb
Labels: good first issue

#4 feat-menu-options-products
  marktplace.rb
Labels: enhancement
